# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
      - group: "DevEnv"
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - group: "ProdEnv"

steps:
  - script: |
      chmod +x print_env.sh
      ./print_env.sh
    displayName: "Print env"

  - task: AzureResourceGroupDeployment@2
    displayName: "Deploy ARM Template with Parameters"
    inputs:
      azureSubscription: ARM example
      resourceGroupName: $(TARGET_RESOURCE_GROUP)
      location: $(LOCATION)
      templateLocation: "Linked artifact"
      csmFile: '$(Agent.BuildDirectory)\infra\azuredeploy.json'
      overrideParameters: |
        -storagePrefix $(STORAGE_PREFIX)
        -storageSKU $(STORAGE_SKU)
        -appServicePlanName $(APP_SERVICE_PLAN_NAME)
        -webAppName $(WEBAPP_NAME)
        -tsResourceGroup $(TS_RESOURCE_GROUP)
        -tsName $(TS_NAME)
        -tsVersion $(TS_VERSION)
        -resourceTags "$(RESOURCE_TAGS)"
      deploymentMode: "Incremental"
