#!/bin/bash

echo "STORAGEPREFIX=${STORAGE_PREFIX}"
echo "STORAGESKU=${STORAGE_SKU}"
echo "APPSERVICEPLANNAME=${APP_SERVICE_PLAN_NAME}"
echo "WEBAPPNAME=${WEBAPP_NAME}"
echo "TSRESOURCEGROUP=${TS_RESOURCE_GROUP}"
echo "TSNAME=${TS_NAME}"
echo "TSVERSION=${TS_VERSION}"
echo "RESOURCETAGS=${RESOURCE_TAGS}"
