name: Azure ARM Deployment

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Map the branches to the corresponding GitHub environments
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Print environment variables
        run: |
          echo "STORAGEPREFIX=${{ vars.STORAGEPREFIX }}"
          echo "STORAGESKU=${{ vars.STORAGESKU }}"
          echo "APPSERVICEPLANNAME=${{ vars.APPSERVICEPLANNAME }}"
          echo "WEBAPPNAME=${{ vars.WEBAPPNAME }}"
          echo "TSRESOURCEGROUP=${{ vars.TSRESOURCEGROUP }}"
          echo "TSNAME=${{ vars.TSNAME }}"
          echo "TSVERSION=${{ vars.TSVERSION }}"
          echo "RESOURCETAGS=${{ vars.RESOURCETAGS }}"

      - name: "Deploy ARM Template with Parameters"
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ vars.TARGETRESOURCEGROUP }}
          template: ./infra/azuredeploy.json
          parameters: storagePrefix=${{ vars.STORAGEPREFIX }} storageSKU=${{ vars.STORAGESKU }} appServicePlanName=${{ vars.APPSERVICEPLANNAME }} webAppName=${{ vars.WEBAPPNAME }} tsResourceGroup=${{ vars.TSRESOURCEGROUP }} tsName=${{ vars.TSNAME }} tsVersion=${{ vars.TSVERSION }} resourceTags=${{ vars.RESOURCETAGS }}
          deploymentMode: Incremental

      - name: "Azure Logout"
        run: |
          az logout
